<?php

/**
 * @file
 * Adds checkbox to the Clean URLs settings form and alters outbound URLs.
 * Disables the Deslash setting GlobalRedirect.
 */

/**
 * Function to add a trailing slash to the path if there isn't one already.
 */

function trailing_slash_add(&$path) {
	$path = preg_replace('/((?:^|\\/)[^\\/\\.]+?)$/isD', '$1/', $path);
}

/**
 * Implements hook_url_outbound_alter().
 */
function trailing_slash_url_outbound_alter(&$path, &$options, $original_path) {
	// If Clean URLs and Trailing Slashes are enabled and not external, front page, or empty path
	if (!empty($GLOBALS['conf']['clean_url']) && variable_get('trailing_slash', 0) && !$options['external'] && $path != '<front>' && !empty($path)) {
		// If not already an alias
		if (!$options['alias']) {
			// Pre-alias, as the only available hook is before aliasing is done and we need to modify the final URL path
			// This is a copy of Drupal core code
			$language = isset($options['language']) && isset($options['language']->language) ? $options['language']->language : '';
			$alias = drupal_get_path_alias($original_path, $language);
			if ($alias != $original_path) {
				$path = $alias;
			}
			// End of Drupal core code
			
			// Mark that the path is now an alias so the alias code isn't needlessly re-run
			$options['alias'] = true;
		}
		
		// Add trailing slash
		trailing_slash_add($path);
	}
}


/**
 * Implements hook_form_FORM_ID_alter().
 */

function trailing_slash_form_system_clean_url_settings_alter(&$form, &$form_state, $form_id) {
	// Add checkbox to enable/disable trailing slashes
	$form['trailing_slash'] = array(

		'#type' => 'checkbox',
		'#title' => t('Enable trailing slashes'),
		'#default_value' => variable_get('trailing_slash', 0),

		'#description' => t('Add a trailing slash to URLs eg. <code>example.com/user/</code>.')
	);
}


/**
 * Implements custom_url_rewrite_outbound().
 * This is for Drupal 6.x support and any Drupal 7.x modules that may use it (eg. GlobalRedirect)
 */

function custom_url_rewrite_outbound(&$path, $options, $original_path) {
	// If Clean URLs and Trailing Slashes are enabled and not external, front page, or empty path, add a trailing slash
	if (!empty($GLOBALS['conf']['clean_url']) && variable_get('trailing_slash', 0) && !$options['external'] && $path != '<front>' && !empty($path)) trailing_slash_add($path);
}


/**
 * Implements hook_form_FORM_ID_alter().
 */

function trailing_slash_form_globalredirect_settings_alter(&$form, &$form_state, $form_id) {
	if (variable_get('trailing_slash', 0)) {
		$form['settings']['deslash'] = array_merge($form['settings']['deslash'], array(
			'#disabled' => TRUE,
			'#default_value' => 0,
			'#description' => '<em>This feature cannot be enabled because <a href="/admin/config/search/clean-urls/">trailing slashes are enabled</a>.</em><br />' . $form['settings']['deslash']['#description']
		));
	}
}